const mongoose = require("mongoose");
const Schema = mongoose.Schema;

let eventSchema = new Schema({
  add: String,
  title: String,
  video_url: String,
  content_rating_class: String,
  categories: Array,
  created_time: String,
  description: String,
  download: Array,
  duration: String,
  has_audio: Boolean,
  height: Number,
  is_playable: String,
  language: String,
  last_user_action_event_date: Number,
  license: String,
  link: String,
  manage_link: String,
  metadata: Array,
  modified_time: String,
  parent_folder: String,
  play: Array,
  player_embed_url: String,
  privacy: Array,
  rating_mod_locked: Boolean,
  release_time: String,
  resource_key: String,
  review_page: Array,
  stats: Array,
  status: String,
  tags: Array,
  transcode: Array,
  type: String,
  upload: Array,
  uploader: Array,
  uri: String,
  user: Array,
  width: Number,
  artists: Array,
  attributes: Array,
  is_featured: String,
  on_demand: String,
  pick_lounge: String,
  tip_something: String,
  subscription: {
    is_featured: Boolean,
    on_demand: Boolean,
    pick_lounge: Boolean,
    tip_something: Boolean,
  },
  video_link: String,
  thumbnail: String,
  background: String,
});

let event = mongoose.model("event", eventSchema);

module.exports = event;
